<a href="https://colab.research.google.com/github/TharunPranavM/python-codes/blob/main/python_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# question 1
# selection and iteration operators
# selection operator
num = int(input('enter a number:'))
if num%2 == 0 :
  print (' the num is even')
else :
  print ('the num is odd')

enter a number:212
 the num is even


In [ ]:
#iteration operators - while and for
num = int(input('enter a num:'))
count = 0
while count <= num:
    print(count)
    count += 1

numbers = list(map(int , input().split()))
sum = 0

for num in numbers:
    sum += num

print("Sum:", sum)

enter a num:2
0
1
2
2 3 4
Sum: 9


In [ ]:
# question 2
# odd or even
num2 = int(input("Enter a number: "))
if num2 % 2 == 0 :
  new = 0
  real =num2
  while num2 > 0:
        digit = num2 % 10
        new = new * 10 + digit
        num2 = num2 // 10
  if real == new:
      print("The number is a palindrome.")
  else:
      print("The number is not a palindrome.")
else :
  a=0
  b=1
  count1 = 0
  while count1 <= num2:
    c = a+b
    a = b
    b = c
    count1 += 1
  print ('the factorial:',c)
  print ('number digit factorial:',len(str(c)))




Enter a number: 212
The number is a palindrome.


In [ ]:
# question 3
# string and its operation
str1 = " Hello, World! "
print(str1.lower())
print(str1.upper())
print(str1.strip())
print(str1.split(","))
print(str1.replace("Hello", "Hi"))
print(str1.find("World"))


 hello, world! 
 HELLO, WORLD! 
Hello, World!
[' Hello', ' World! ']
 Hi, World! 
8


In [ ]:
# string slicing
str1 = " Hello, World! "
print(str1[0:5])
print(str1[7:])
print(str1[:5])
print(str1[-6:])
print(str1[0:11:2])
print(str1[::3])
print(str1[-6:-1])
print(str1[:-8])
print(str1[::-1])

 Hell
 World! 
 Hell
orld! 
 el,Wr
 l,od
orld!
 Hello,
 !dlroW ,olleH 


In [ ]:
# question 4
str1 = 'hello world'
str2 = 'hello'
count2 = 0
for i in str2:
  for j in str1:
    if j == i :
      count2 +=1
      break
    else :
      continue
if count2 == len(str2):
  print ('YES')
else:
  print ('NO')

YES


In [ ]:
# question 5 - list and its operation
my_list = [1, 2, 3]
my_list.append(4)
print(my_list)
my_list.extend([5, 6, 7])
print(my_list)
my_list.insert(2, 10)
print(my_list)
my_list.remove(4)
print(my_list)
item = my_list.pop(3)
print(item)
print(my_list)
my_list.sort()
print(my_list)
my_list.reverse()
print(my_list)
my_list = [1, 2, 3, 4, 5]
sub_list = my_list[1:4]
print(sub_list)
# Concatenation
list1 = [1, 2, 3]
list2 = [4, 5, 6]
concatenated_list = list1 + list2
print(concatenated_list)

[1, 2, 3, 4]
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 10, 3, 4, 5, 6, 7]
[1, 2, 10, 3, 5, 6, 7]
3
[1, 2, 10, 5, 6, 7]
[1, 2, 5, 6, 7, 10]
[10, 7, 6, 5, 2, 1]
[2, 3, 4]
[1, 2, 3, 4, 5, 6]


In [ ]:
# question 6 - postive and negative indexing
my_list2 = [10, 20, 30, 40, 50]

# Positive indexing
print(my_list2[0])
print(my_list2[2])
print(my_list2[4])

# Negative indexing
print(my_list2[-1])
print(my_list2[-3])
print(my_list2[-5])

10
30
50
50
30
10


In [ ]:
# question 7
new_list = list(map(int, input().split()))
for i in range(len(new_list)-1):
  if new_list[i] > new_list[i+1]:
    print ('the list is not in ascending order')
  else:
    print ('the list is in ascending order')



2 3 4 5
the list is in ascending order
the list is in ascending order
the list is in ascending order


In [ ]:
# question 8 - tuples and its operation
tuple1 = (1, 2, 3, 4, 5)
tuple2 = (6, 7, 8)

# Concatenation
tuple3 = tuple1 + tuple2
print(tuple3)

# Repetition
tuple4 = tuple1 * 3
print(tuple4)

# Indexing
print(tuple1[0])
print(tuple1[-1])

# Slicing
print(tuple1[1:3])

# Membership
print(1 in tuple1)
print(6 in tuple1)


(1, 2, 3, 4, 5, 6, 7, 8)
(1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5)
1
5
(2, 3)
True
False


In [ ]:
# question 9
tuple_1 = tuple(map(str, input().split()))
str_1 = ''
for i in tuple_1:
  str_1 = str_1 + i

print (str_1)

s t r i n g
string


In [ ]:
# question 10
tuple_2 = tuple(map(int , input().split()))
new_tup = tuple_2[::-1]
print (new_tup)


2 3 4 5 6 
(6, 5, 4, 3, 2)


In [ ]:
# question 11 - set and its operation
set1 = {1, 2, 3, 4, 5}
set2 = {2, 4, 6, 8}

# Adding elements
set1.add(6)
set2.add(1)

# Removing elements
set1.remove(3)
set2.remove(4)

# Checking for membership
print(1 in set1)
print(7 in set1)

# Set operations
print(set1 | set2)
print(set1 & set2)
print(set1 - set2)
print(set1 ^ set2)

# isdisjoint
print(set1.isdisjoint(set2))

# issubset
print(set1.issubset(set2))

# issuperset
print(set2.issuperset(set1))

# pop
print(set1.pop())

# remove
print(set1.remove(2))

# clear
set1.clear()
print(set1)


True
False
{1, 2, 4, 5, 6, 8}
{1, 2, 6}
{4, 5}
{4, 5, 8}
False
False
False
1
None
set()


In [ ]:
# question 12
set1=set(map(int, input('enter set of values :').split()))
subset=set(map(int, input('enter subset of values :').split()))
print(subset.issubset(set1))
# different method
'''for item in subset:
  if item not in set1:
    print ("it isn't subset")
    break

  else:
    print ("it is subset")'''

enter set of values :2 3 4 5
enter subset of values :2 3 5 6
False


'for item in subset:\n  if item not in set1:\n    print ("it isn\'t subset")\n    break\n\n  else:\n    print ("it is subset")'

In [ ]:
# question 13 - dictionaries and its operations
dict = {"key1": "value1", "key2": "value2"}

# Accessing elements
print(dict["key1"])

# Adding elements
dict.update({"key3": "value3"})
# Removing elements
dict.pop("key2")
# Checking for membership
print("key2" in dict)
# Keys
print(dict.keys())
# Values
print(dict.values())
# Items
print(dict.items())
# Len
print(len(dict))
# Clear
dict.clear()
print(dict)




value1
False
dict_keys(['key1', 'key3'])
dict_values(['value1', 'value3'])
dict_items([('key1', 'value1'), ('key3', 'value3')])
2
{}


In [ ]:
# question 14
dict = {"fruit1": "apple", "fruit2": "orange"}


for key in dict:
  print(key, dict[key])


for value in dict.values():
  print(value)


for key, value in dict.items():
  print(key, value)



fruit1 apple
fruit2 orange
apple
orange
fruit1 apple
fruit2 orange


In [ ]:
#question 15
# compute using numpy

''' to install numpy:-
   -> pip install numpy   '''

import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

# Initialize arrays of zeros and ones
zeros_array = np.zeros((3, 4))
ones_array = np.ones((2, 2))
print(zeros_array)
print(ones_array)

# Create a range of values with linspace
linspace_array = np.linspace(0, 10, 5)
print(linspace_array)

# Create a range of values with arange
arange_array = np.arange(0, 10, 2)
print(arange_array)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[ 0.   2.5  5.   7.5 10. ]
[0 2 4 6 8]


In [ ]:
# question 16
my_list = list(map(int,input('enter a list of numbers : ').split()))
arr1 =np.array(my_list)
arr1

enter a list of numbers : 2 4 5 6 7 8


array([2, 4, 5, 6, 7, 8])

In [ ]:
# question 17
my_list = list(map(int,input('enter a list of numbers : ').split()))
arr1 =np.array(my_list)
print(arr1)
my_tup = tuple(map(int,input('enter a list of numbers : ').split()))
arr2 =np.array(my_tup)
print(arr2)

enter a list of numbers : 2 3 4 56 6 7
[ 2  3  4 56  6  7]
enter a list of numbers : 3 4 5 6 7 8 9
[3 4 5 6 7 8 9]


In [ ]:
# question 18
'''pip install pandas '''
import pandas as pd
# Creating a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 28],
        'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']}

df = pd.DataFrame(data)
print(df)

'''Creating a DataFrame from a CSV file
df1 = pd.read_csv('data.csv')'''

# Accessing columns
print(df['Name'])
print(df.Age)

# Accessing rows
print(df.loc[0])

# Filtering data
young_people = df[df['Age'] < 30]

# Adding new columns
df['Salary'] = [50000, 60000, 75000, 45000]

# Removing columns
df.drop('City', axis=1, inplace=True)

# Renaming columns
df.rename(columns={'Name': 'Full Name'}, inplace=True)

# Handling missing values
df.dropna(inplace=True)
df.fillna(0, inplace=True)


      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago
0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object
0    25
1    30
2    35
3    28
Name: Age, dtype: int64
Name       Alice
Age           25
City    New York
Name: 0, dtype: object


In [ ]:
# question 19
arr1 =np.array([[1, 2], [3, 4], [5, 6]])
df = pd.DataFrame(arr1)
print(df)

series1 = pd.Series([10, 20, 30, 40, 50])
df2 = pd.DataFrame(series1)
print(df2)

   0  1
0  1  2
1  3  4
2  5  6
    0
0  10
1  20
2  30
3  40
4  50


In [ ]:
# question 20

data1 = {'A': 10, 'B': 20, 'C': 30}
series1 = pd.Series(data1)

data2 = {'A': 5, 'B': 15, 'C': 25}
series2 = pd.Series(data2)

# Addition
add_result = series1 + series2
print("Addition Result:")
print(add_result)

# Subtraction
sub_result = series1 - series2
print("\nSubtraction Result:")
print(sub_result)

# Multiplication
mul_result = series1 * series2
print("\nMultiplication Result:")
print(mul_result)

# Division
div_result = series1 / series2
print("\nDivision Result:")
print(div_result)


Addition Result:
A    15
B    35
C    55
dtype: int64

Subtraction Result:
A    5
B    5
C    5
dtype: int64

Multiplication Result:
A     50
B    300
C    750
dtype: int64

Division Result:
A    2.000000
B    1.333333
C    1.200000
dtype: float64


In [ ]:
# question 21

# Sample data for the DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago'],
    'Salary': [50000, 60000, 75000, 45000]
}

df = pd.DataFrame(data)

# Retrieving data from the DataFrame

print("DataFrame:")
print(df)

# Accessing specific columns
print("\nName Column:")
print(df['Name'])

# Accessing multiple columns
print("\nName and Age Columns:")
print(df[['Name', 'Age']])

# Accessing rows using loc
print("\nFirst Row using loc:")
print(df.loc[0])

# Accessing specific rows and columns using loc
print("\nName and Age of the second row using loc:")
print(df.loc[1, ['Name', 'Age']])


# Manipulating data in the DataFrame
# Adding a new column
df['Bonus'] = [2000, 3000, 2500, 1800]

# Updating values in a column based on a condition
df.loc[df['Age'] < 30, 'Bonus'] += 500

# Removing a column
df.drop('City', axis=1, inplace=True)

# Filtering rows based on a condition
young_employees = df[df['Age'] < 30]

# Sorting the DataFrame by a column
sorted_df = df.sort_values(by='Salary', ascending=False)

# Aggregating data
average_salary = df['Salary'].mean()

# Printing the modified DataFrame
print("\nModified DataFrame:")
print(df)

# Printing the young employees DataFrame
print("\nYoung Employees:")
print(young_employees)

# Printing the sorted DataFrame
print("\nSorted DataFrame:")
print(sorted_df)

# Printing the average salary
print("\nAverage Salary:", average_salary)


DataFrame:
      Name  Age           City  Salary
0    Alice   25       New York   50000
1      Bob   30  San Francisco   60000
2  Charlie   35    Los Angeles   75000
3    David   28        Chicago   45000

Name Column:
0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

Name and Age Columns:
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   28

First Row using loc:
Name         Alice
Age             25
City      New York
Salary       50000
Name: 0, dtype: object

Name and Age of the second row using loc:
Name    Bob
Age      30
Name: 1, dtype: object

Modified DataFrame:
      Name  Age  Salary  Bonus
0    Alice   25   50000   2500
1      Bob   30   60000   3000
2  Charlie   35   75000   2500
3    David   28   45000   2300

Young Employees:
    Name  Age  Salary  Bonus
0  Alice   25   50000   2500
3  David   28   45000   2300

Sorted DataFrame:
      Name  Age  Salary  Bonus
2  Charlie   35   75000   2500
1      Bob   30   60000   